network-name = "Abelian Testnetwork"
rpc-host = "testnet-rpc-00.abelian.info"
rpc-port = ""
rpc-user = "="
rpc-pass = "ULlXc/+Y3KGQ="
disable-tls = false
wallet-name = ""
enable-indexer = true
indexer-listen-address = ""
indexer-listen-target-confirmations = 1

[bridge]
eth-rpc-url = ""
eth-priv-key = ""
contract-address = "0x50c342af114d6f7F70d7E14FC351012651F80E97"
abi = "abi.json"
aa-b2-api = ""
enable-withdraw-listener = false
deposit = ""
withdraw = ""
unisat-api-key = ""
publickeys = []
time-interval = 10
multisig-num = 0
enable-rollup-listener = false

