network-name = "mainnet"
rpc-host = "docs-demo.btc.quiknode.pro"
rpc-port = ""
rpc-user = ""
rpc-pass = ""
disable-tls = false
wallet-name = ""
enable-indexer = true
indexer-listen-address = "34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo"
indexer-listen-target-confirmations = 1

[bridge]
eth-rpc-url = "http://124.243.137.251:8123"
eth-priv-key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
contract-address = "0x4A679253410272dd5232B3Ff7cF5dbB88f295319"
abi = ""
enable-eoa-transfer = false
aa-b2-api = "localhost:9002"
aa-particle-rpc = "https://rpc.particle.network/evm-chain"
aa-particle-project-id = "11111"
aa-particle-server-key = "22222"
aa-particle-chain-id = 1102
gas-price-multiple = 2
b2-explorer-url = ""
enable-withdraw-listener = false
deposit = ""
withdraw = ""
unisat-api-key = ""
publickeys = []
time-interval = 10
multisig-num = 0
enable-rollup-listener = false
enable-vsm = false
vsm-internal-key-index = 0
vsm-iv = ""
local-decrypt-key = ""
local-decrypt-alg = ""

[eps]
enable-eps = false
url = ""
authorization = ""
