version: "3.5"
networks:
  default:
    name: abelian-l2
services:
  pg:
    container_name: indexer-db
    image: postgres:14.10
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/postgres/datadir:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=abe_user
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=abe_indexer
    ports:
      - 5432:5432
  mysql:
    container_name: committer-db
    image: mysql:8.0
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./docker-entrypoint-initdb.d/mysql.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/mysql/datadir:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=abe_committer
    ports:
      - 3306:3306
  bridge:
    container_name: bridge-db
    image: mysql:8.0
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./docker-entrypoint-initdb.d/bridge.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/mysql2/datadir:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=abe_bridge
    ports:
      - 3307:3306
